language: objective-c
xcode_project: App/iOS-Custom-UIs.xcodeproj
xcode_scheme: iOS-Custom-UIs
xcode_sdk: iphonesimulator

before_install:
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi